{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-json-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "prometheus-json-exporter.name" . }}
    chart: {{ template "prometheus-json-exporter.chart" . }}    
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  
  annotations:
  {{- if .Values.serviceAccount.annotations }}
    {{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
{{- end }}
