apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-json-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  labels:
    app: {{ template "prometheus-json-exporter.name" . }}
    chart: {{ template "prometheus-json-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: container-port
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    app: {{ template "prometheus-json-exporter.name" . }}
    release: {{ .Release.Name }}
